### ISSUE TITLE
test: fuzz warp durations

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#126]
Several tests asserts that some event must happen after a delay. If this delay is 60 seconds, the test usually warps forward 60 seconds and asserts the successful case. A more robust approach to fuzzing would fuzz the delay such that all reasonably amounts > 60 were tried (e.g. 60 seconds to 100 years).

**Comment by jcliff** [comment]
Hey, @varunsrin. Would love to help out and learn in the process. I'm wondering if this patch is on the right track? Or if you had another method/technique in mind?
[wip-fuzz.patch](https://github.com/farcasterxyz/contracts/files/10516029/wip-fuzz.patch)

**Comment by varunsrin** [comment]
directionally this looks great! want me to assign the ticket to you?

**Comment by jcliff** [comment]
sure, you can assign it to me. here is a stab at adding coverage to the most obvious tests.

https://github.com/farcasterxyz/contracts/pull/167

**Comment by varunsrin** [comment]
need to review whether any other tests need warp fuzz coverage
