### ISSUE TITLE
perf: consider reverting payable optimizations

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#129]
Several functions were made payable to save very small amounts of gas in IDRegistry, NameRegistry and BundleRegistry. Consider reverting them since the savings are small and the inconvenience to users who accidentally send funds may not be worth it.

**Comment by jaglinux** [comment]
I can take up this issue.

**Comment by varunsrin** [comment]
go for it!

**Comment by varunsrin** [comment]
some changes were completed [here](https://github.com/farcasterxyz/contracts/pull/145/files), others are no longer relevant with the deprecation of the NameRegistry
