### ISSUE TITLE
feat: allow reclaiming multiple usernames

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#153]
**What is the feature you would like to implement?**
Reclaim should allow moving multiple usernames to multiple addresses in a single transaction.

**Why is this feature important?**
Performing reclaims can become expensive and tedious with the current design since 2 separate txns are required to reclaim and restore a name to a user.

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
The `reclaim` function should accept an array of ReclaimAction structs, each of which contains a username and a destination address. If any names being transferred will expire in < 1 week, it should renew it for 1 week.

**Comment by gaavar** [comment]
Hello! Can I work on this issue?

**Comment by varunsrin** [comment]
yes! 

btw, what is your farcaster username?

**Comment by gaavar** [comment]
It's 0xanu ! 

I read the current `reclaim` function in `NameRegistry`. 

Inside the new `reclaim` function, for each of the ReclaimAction structs, we would call `_transfer` to the address contained inside the struct instead of the `pool` address. Is my understanding correct?

**Comment by gaavar** [comment]
It's 0xanu 🙂

I reviewed the current reclaim function in NameRegistry.

Inside the new reclaim function, for each of the ReclaimAction structs, we would call _transfer to the address contained inside the struct instead of the pool address. Is my understanding correct?

**Comment by varunsrin** [comment]
i think that's a great starting point. if there is a more gas efficient way to do transfers by writing a batch transfer method i'm open to that as well.

**Comment by gaavar** [comment]
Hello!

I wrote an initial draft for the new `reclaim`. A few comments/questions:
- I noticed that if I define the new function as `reclaim` (function overloading), it causes the pre-commit hook `forge snapshot --check --match-contract Gas` to fail.  I found `recl` as the function name doesn't throw that error so I am using that for now! 
- For testing, I was thinking of following the pattern in `NameRegistry.t.sol`'s `MODERATOR TESTS` with multiple users like Alice, Bob, Carol, Dan etc (where applicable). Are there any other tests or scenarios that I should consider?
- I will look into batch transfers for gas optimizations after we have a function that meets our requirements with appropriate tests.

**Comment by varunsrin** [comment]
1. what is the signature you're thinking of for the new reclaim function? there might be a way to write it so that its ergonomic and gas efficient for single reclaims and multiple reclaims. in that case, its fine to replace the old one. otherwise you can write something like reclaim_batch 

2. using the existing test suite sounds fine , i can leave more feedback once you have a draft

**Comment by gaavar** [comment]
Hi! I created a pull request [here](https://github.com/farcasterxyz/contracts/pull/168) to discuss this further!
