### ISSUE TITLE
perf: reduce gas usage in batch methods

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#156]
**What is the feature you would like to implement?**
Explore different approaches to reducing gas in batch methods

**Why is this feature important?**
Batch methods like trustedBatchRegister (and eventually reclaim) will be used on mainnet and reducing gas usage might save ETH

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
Consider packing calldata into more tightly packed structs, using fixed array lengths

**Comment by jaglinux** [comment]
With PR #158 , 
Diff in "BundleRegistryTest::testTrustedBatchRegister(address,address,address)": consumed "(runs: 512, μ: 482819, ~: 482819)" gas, expected "(runs: 512, μ: 483008, ~: 483008)" gas

**Comment by jaglinux** [comment]
Batch functions are not covered under user gas saving tests.

**Comment by varunsrin** [comment]
Closing since BundleRegistry was removed: https://github.com/farcasterxyz/contracts/pull/224
