### ISSUE TITLE
chore: review trailofbits security guidelines

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#174]
**What is the feature you would like to implement?**

Review new security recommendations from TrailOfBits here: https://secure-contracts.com/ and see if we need to make any changes. 

**Why is this feature important?**
 Make sure we're following the latest and best recommended security practices

**Will the protocol spec need to be updated??**
No

**Comment by varunsrin** [comment]
Reviewed guidelines, there are a few more pieces to resolve before we close this issue: 

1. Configure slither in CI #70 
2. Add slither erc and upgradeability checks once [this issue](https://github.com/crytic/crytic-compile/issues/397) is resolved
3. Resolve or ignore the slither info warning `NameRegistry (src/NameRegistry.sol#29-1149) needs to be initialized by NameRegistry.initialize(string,string,address,address) (src/NameRegistry.sol#330-357).
Reference: https://github.com/crytic/slither/wiki/Upgradeability-Checks#initialize-function` in the upgradeability check, since it is not clear what the issue is
4. Resolve or ignore the slither warnings about returning bools for NameRegistry.transferFrom and NameRegistry.approve since ERC-721 does not require them.

**Comment by varunsrin** [comment]
resolved general slither warnings here: https://github.com/farcasterxyz/contracts/pull/189

**Comment by 0xalpharush** [comment]
Wrt #3, there is an informational [detector](https://github.com/crytic/slither/wiki/Upgradeability-Checks#initialize-function) which identifies initialize functions which should be called upon deployment. This can be ignored with `--ignore-informational`.

**Comment by varunsrin** [comment]
closing, we've deployed the contracts to mainnet and completed the audits
