### ISSUE TITLE
Make the Namespace contract upgradeable

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#18]
We expect to change some of the logic in the Namespace contract as Farcaster evolves. For instance, we may want to change the duration of auctions or support a new EIP to increase composability. 

Upgradeability of this contract does not affect [sufficient decentralization](https://www.varunsrinivasan.com/2022/01/11/sufficient-decentralization-for-social-networks) of the Farcaster network. Usernames are cosmetic conveniences and do not affect a user's relationship with their content or follow graphs.  

Our goal is to find a solution that: 

1. Allows all parts of the logic to be changed easily 
2. Preserves all state between upgrades
3. Minimizes gas costs for contract *interactions* 
4. Uses well audited libraries instead of custom logic
5. Is compatible with meta-transactions as defined in [EIP-2771](https://eips.ethereum.org/EIPS/eip-2771)
6. Is easy to implement and test with the [foundry](https://github.com/foundry-rs/foundry) toolchain

## Options Under Consideration

We're leaning towards Option A assuming it has the lowest gas costs. 

### A - UUPS Proxy 
Open Zeppelin's [UUPS proxy](https://docs.openzeppelin.com/contracts/4.x/api/proxy#UUPSUpgradeable) implements [EIP-1822](https://eips.ethereum.org/EIPS/eip-1822) which solves many of these issues. We've also used it in v1 of Farcaster contracts with no issues for over a year. 

- Integration with foundry needs to be investigated.
- Gas costs need to be compared to other options.

### B - Diamonds 
The Multi-Facet Proxy Pattern or [Diamonds](https://eips.ethereum.org/EIPS/eip-2535) offers a more flexible upgrade pattern where logic can be sub-divided into smaller facets, each of which can be upgraded independently. The main benefit is that our contract can extend beyond the 24kB limit, which we may approach if we add significant functionality in the future.  The main drawbacks are that the pattern is fairly new, introduces a lot of complexity.  and there aren't many well audited and battle tested libraries. Also, OZ [does not intend to fully support](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2793#issuecomment-983230289) this pattern.

There is also an Option B' to implement Genius Ventures' [fork of OZ](https://github.com/GeniusVentures/openzeppelin-contracts-diamond) that implements Upgradeable OZ contracts with the Diamond Storage pattern. OpenZeppelin has indicated that they **may** adopt this as standard when the next major version comes out, but that may not be for a while. 

- Gas costs need to be compared to other options.

### C - Beacon Proxies 
The Beacon proxy pattern introduced in Dharma allows upgrading multiple proxies cheaply. This doesn't immediately have benefits for a singleton contract, and will likely have higher gas costs due to the extra call to the beacon before executing the function. 

- Gas costs need to be compared to other options.

### Migrate to new Contract
This is feasible for parallelizable contracts like Uniswap but not for singletons like the Namespace. Also, migration in Uniswap only requires a small number of transactions from LP's over a flexible time window. Farcaster users will be much more numerous and must upgrade within a narrow time window, which is infeasible. 

### Configurable Parameters
Admin controlled parameters work for only a narrow set of pre-determined changes like, auction duration. They also introduce more complexity and make it harder to model and test behaviors. 

## References

- [The State of Smart Contract Upgrades](https://blog.openzeppelin.com/the-state-of-smart-contract-upgrades/#upgrade-patterns)
- [Understanding Diamonds on Ethereum](https://dev.to/mudgen/understanding-diamonds-on-ethereum-1fb)
- [AppStorage Pattern](https://dev.to/mudgen/appstorage-pattern-for-state-variables-in-solidity-3lki)

**Comment by gsgalloway** [comment]
Agree with the choice to use UUPS. Diamonds is going to add marginally more value at the cost of more complexity and less support with other ecosystem tools

**Comment by varunsrin** [comment]
Decision: we are moving forward with Option A
