### ISSUE TITLE
test: add coverage to BundleRegistry.register for overpayment

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#204]
**What is the issue?**
BundleRegistry.register() does not have test coverage for the [return of funds](https://github.com/farcasterxyz/contracts/blob/17bc8dfef87ab66d56b9a790efc21d4019974a5c/src/BundleRegistry.sol#L87), so we should add tests that check for this behavior, similar to IdRegistry and NameRegistry

**Comment by ilhamfp** [comment]
Hi @varunsrin opened a PR [here](https://github.com/farcasterxyz/contracts/pull/207) to help :)

**Comment by varunsrin** [comment]
Closing since BundleRegistry was removed: https://github.com/farcasterxyz/contracts/pull/224
