### ISSUE TITLE
feat: write thorough tests for the bundler

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#242]
**What is the feature you would like to implement?**

Thoroughly test all aspects of the bundler contract

**How should this feature be built? (optional)**

- [x] testFuzzTrustedBatchRegister should accept a variable length array instead of fixed items
- [x] Bundler should be tested for ownership transfer via Ownable
- [ ] Bundler should have a deploy script and tests to ensure that all the contracts work correctly

**Comment by varunsrin** [comment]
some items are handled here: https://github.com/farcasterxyz/contracts/pull/243

**Comment by horsefacts** [comment]
@varunsrin Now that we have a [deployment test](https://github.com/farcasterxyz/contracts/blob/main/test/Deploy/Deploy.t.sol) in place, I think the last item here is complete.
