### ISSUE TITLE
Reserving usernames without Merkle Trees

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#28]
## Rationale

Users who have registered specific names on the Rinkeby contract should be able to retain ownership of these names when we move to Görli and mainnet. A Merkle Tree based approach was [previously implemented](https://github.com/farcasterxyz/contracts/pull/26) to reserve names.  We propose replacing this with a a simpler model which has lower gas fees and does not require the user to come online at a specific time. 

## Proposal 

Once the contracts are launched on the new network, registrations can only be made from a special address for 48 hours (the reserved registrant). A service that controls this address will automatically register all names that were tagged for migration to the same address that owned them on the previous network. The Farcaster team will determine the set of active usernames to migrate, and the exact process is outside the scope of this ticket. 

### Contract Modifications

The existing `preregister` method is modified to stop checking for a merkle proof and will instead check that the `msg.sender` matches the `relayAddress`. Unlike the `register` method, it will not validate usernames (to save gas), will not require a commit (since front-running is not possible) and does not charge for registration. 

```solidity
function preregister(address to, bytes16 username)
```

### Rinkeby to Görli

Since the Hubs are not yet active, this migration will result in a hybrid state where v2 contracts will live side-by-side with v2 data storage layer. Users who are migrating will need to:

- Acquire an ID from the Account Registry into the same address as the username 
- Re-sign and re-upload all of their messages to their v1 Host according to the new v2 file format

### Görli to Mainnet

The Hubs will be active during this migration, which will happen in 2023. A new set of "mainnet Hubs" will be spun up along side the Gorli hubs. Tentatively, users will need to: 

- Claim an account ID on mainnet
- Broadcast an off-chain message to mainnet hubs to connect their id and username
- Re-sign and re-broadcast all messages from the gorli hubs to the mainnet hubs.

**Comment by pfletcherhill** [comment]
This sounds good to me! One small, clarifying question: we're able to change the pre-registration period from 48 hours to another time period for mainnet if need be, right?

**Comment by varunsrin** [comment]
Yes, that's configurable before deploy
