### ISSUE TITLE
bug: idregistry state cannot be frozen for a future upgrade

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#295]
**What is the bug?**
There is no way to freeze the state of IdRegistry, which is important for a safe upgrade in case a bug is discovered in the future. The closest function is pause, which does not prevent transfers or recoveries. Consider extending pause to freeze all state or add a new one-way method like deprecate which freezes the contract entirely.

**Comment by horsefacts** [comment]
@varunsrin I think this was closed by #301 Anything remaining?
