### ISSUE TITLE
IDRegistry should allow setting a home Hub URL

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#34]
The IDRegistry should let each ID specify a `home` Hub. 

The `home` is the Hub that the user claims they are using to broadcast new messages onto the network. There is no downside to declaring one Hub as a the home and then using a different Hub later without updating the home. But if a user were to follow this pattern, it has a few benefits for them: 

1. A Hub that is unable to discover messages for a user from its peers can always query the `home` Hub.
2. A Hub can develop a reliability score for its peers by comparing their state to each user's home state.

Therefore, users who want to maximize deliverability of their messages will always be incentivized to set and respect the `home` Hub URL.

### Implementation

The home property isn't required at registration since users may not know their home URL yet and it increases gas costs for users who do not want this functionality. Instead, we provide a method to update it at any time and an alternative registration method that can set the HomeURL in a single transaction:

- `event ChangeHome(uint256 indexed id, string url)` -- a new event that is emitted when the home url is updated
- `changeHome(string url)` -- emits `ChangeHome` if the caller has an id 
-  `registerWithHome(address recoveryAddress, string url)` -- calls `register` and then emits `ChangeHome`

Home URL changes are emitted as events and not stored since this is gas efficient. To determine the current Home for a given user, filter the events by `id` and type and select the latest emitted one. 

### Assumptions

1. Any Hub (like an Ethereum Node) can be represented by a simple HTTPS path like `https://www.farcaster.xyz/hub`.

2. Users are responsible for setting the URL correctly and we should assume that some of the URLs will be malformed.

**Comment by varunsrin** [comment]
Make sure to update this `home` URL concept in the protocol specification.

**Comment by sanjayprabhu** [comment]
`registerWithHome` would also require the `recoveryAddress` param, right?

May also be worth exposing a view function to get the current home for an account. Querying events to get the current state is fine, but IMO more idiomatic to just ask the contract. Not a big deal though.

Looks good otherwise 👍

**Comment by varunsrin** [comment]
To implement a view function we'd also need to SSTORE every string which can get expensive and discourage usage of the feature. The tradeoff is that we make it cheaper for users and slightly harder for developers since they have to query events and have a node that has archival data to get a fully accurate picture.  

I'd bias towards encouraging people to store data, even if its slightly more difficult for developers.

**Comment by sanjayprabhu** [comment]
Ah, I missed that `changeHome` only emits and doesn't store. Makes sense then. Agree with the tradeoff, saving 20k in gas is worth a little additional difficulty reading. I'm not too worried about requiring an archive node, esp. for ETH.
