### ISSUE TITLE
testing: symbolic testing with halmos 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#396]
**What is the feature you would like to implement?**
Test all contracts symbolically with Halmos 

**Why is this feature important?**
Symbolic testing helps us identifying issues more thoroughly than fuzzing alone.

**Comment by horsefacts** [comment]
We merged `IdRegistry` symtests and set up Halmos in https://github.com/farcasterxyz/contracts/pull/397. We have some follow up work to get the `KeyRegistry` tests working. I'm gonna close this and split out a separate issue for `KeyRegistry`.
