### ISSUE TITLE
feat: unable to log in 

### ISSUE THREAD

**Issue by rishiarch4** [farcasterxyz/contracts#406]
I purchased year subscription and minted NFT and I downloaded the app it says unable to load purchases ty to login with another device why ? 
![Screenshot_2024-01-30-22-08-21-58_ccc83685d717c1e672ab4103eeb0a617](https://github.com/farcasterxyz/contracts/assets/153585838/ca4fef25-ecf8-47da-a972-c5f8f3b3e10d)

**Comment by varunsrin** [comment]
please email support@merklemanufactory.com from the email you used to sign up
