### ISSUE TITLE
bug: Popup's

### ISSUE THREAD

**Issue by hypenikkkkk** [farcasterxyz/contracts#416]
* What is the bug?

During the quests far.school, the blocks that pop up during the successful completion of the quest do not disappear themselves, thus taking up all the free space on the screen.

Solution*

I suggest putting a timeout to close the popup.

PC:

![image](https://github.com/farcasterxyz/contracts/assets/153740702/b148766e-2d65-4355-b428-70ca04c0808f)

IOS:

![image](https://github.com/farcasterxyz/contracts/assets/153740702/ee590338-a9b5-4875-80f8-4fc92b988d4e)

**Comment by hypenikkkkk** [comment]
This bug is already more than two months old...

**Comment by hypenikkkkk** [comment]
https://warpcast.com/hypenik/0xdcf545ee

**Comment by varunsrin** [comment]
Far.school is not operated by Farcaster
