### ISSUE TITLE
bug: mapping syntax error in src/IdRegistry.sol

### ISSUE THREAD

**Issue by Rufusemmanuel** [farcasterxyz/contracts#435]
The syntax for the mappings is incorrect. You should use a single => instead of specifying the mapping type twice. Here’s how the correct syntax should look:

mapping(address => uint256) public idOf;
mapping(uint256 => address) public custodyOf;
mapping(uint256 => address) public recoveryOf;

**Comment by varunsrin** [comment]
the syntax is fine, these contracts are deployed and work live
