### ISSUE TITLE
ci: add slither

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/contracts#70]
adding slither to our ci would be useful for catching issues as they come up, as long as it can be executed in a reasonable amount of time and does not have too many false positives

**Comment by varunsrin** [comment]
a template for this is now available here: https://github.com/ScopeLift/foundry-template

**Comment by GarrettJMU** [comment]
Missed this already had a PR - happy to close mine but this should work.

https://github.com/farcasterxyz/contracts/pull/192/files

**Comment by varunsrin** [comment]
Don't seem to be able to get this below 11 minutes, which may not make sense for a CI process that runs on every small change. It may be faster to just have a manual process of running slither and fixing issues before release, since its such a manual process anyway.
